LAB6/app/models.py
from flask_login import UserMixin
from __init__ import db


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(10000))
    name = db.Column(db.String(1000))

LAB6/app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Email, Length, EqualTo


class SignupForm(FlaskForm):
    name = StringField('Имя', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Пароль', validators=[DataRequired()])
    confirm_password = PasswordField('Подтверждение пароля', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Зарегистрироваться')


class LoginForm(FlaskForm):
    email = StringField("Email: ", validators=[Email("Некорректный email")])
    password = PasswordField("Пароль: ", validators=[DataRequired(), Length(min=4, max=100,
                                                                            message="Пароль должен быть от 4 до 100 "
                                                                                    "символов")])
    remember = BooleanField("Запомнить", default=False)
    submit = SubmitField("Войти")

LAB6/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

app = Flask(__name__, template_folder='templates')
app.config['SECRET_KEY'] = '417-290-505'
app.config.from_object('config')
db = SQLAlchemy(app)
login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.init_app(app)

LAB6/app/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__)

LAB6/app/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import current_user, login_user, login_required, logout_user
from __init__ import login_manager
from .models import User, db
from .forms import LoginForm, SignupForm
from werkzeug.security import check_password_hash, generate_password_hash

users = Blueprint('users', __name__)
users_list = []


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@users.route('/')
def index():
    if current_user.is_authenticated:
        return render_template('index.html', title='Home', user=current_user)
    return redirect(url_for('users.login'))


@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        user = User.query.filter_by(email=email).first()

        if user and check_password_hash(user.password, password):
            login_user(user)
            return redirect(url_for('users.index'))
        else:
            flash('Invalid email or password', 'error')
            return render_template('login.html', title='Login', form=form)
    return render_template('login.html', title='Login', form=form)


@users.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        password = form.password.data

        if User.query.filter_by(email=email).first():
            flash('User already exists', 'error')
        else:
            new_user = User(email=email, password=generate_password_hash(password), name=name)
            db.session.add(new_user)
            db.session.commit()
            return redirect(url_for('users.login'))

    return render_template('signup.html', title='Sign Up', form=form)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))

LAB6/main.py
import os
from __init__ import app
from __init__ import db
from app.routes import users


app.register_blueprint(users)


if __name__ == '__main__':
    try:
        with app.app_context():
            db.create_all()
            print('ok')
    except Exception as e:
        print(f"Error during table creation: {str(e)}")
    app.run(debug=True)

LAB6/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
</head>
<body>
    <header>
        <h1>ЛАБОРАТОРНАЯ РАБОТА №6</h1>
    </header>

    <main>
            <p>Привет, {{ user.name }}!</p>
            <p>Это основная страница лабораторной работы №6, здесь вы сможете скачать файл с методическими указаниями</p>
            </p><a href="https://disk.yandex.ru/d/CkyMOdfwrlWr2w" download>Ссылка на скачивание с Я.Диска</a></p>
            <a href="{{ url_for('users.logout') }}">Выход</a>
    </main>
</body>
</html>

LAB6/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
</head>
<body>
    <header>
        <h1>Вход в аккаунт</h1>
    </header>

    <main>
        <form method="POST" action="{{ url_for('users.login') }}">
            {{ form.csrf_token }}
            <label for="email">Email:</label>
            {{ form.email(class="form-control", placeholder="Введите email", required=true) }}
            <br>
            <label for="password">Пароль:</label>
            {{ form.password(class="form-control", placeholder="Введите пароль", required=true) }}
            <br>
            {{ form.submit(class="btn btn-primary") }}
        </form>
        <br>

        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <br class="flashes">
                    {% for category, message in messages %}
                        <li class="{{ category }}">{{ message }}</li>
                    {% endfor %}
                <br>
            {% endif %}
        {% endwith %}
        <p>Еще нет аккаунта? <a href="{{ url_for('users.signup') }}">Зарегистрируйтесь здесь</a>.</p>
    </main>
</body>
</html>

LAB6/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
</head>
<body>
    <header>
        <h1>Регистрация</h1>
    </header>

    <main>
        <form method="POST" action="{{ url_for('users.signup') }}">
            {{ form.csrf_token }}
            <label for="name">Имя:</label>
            {{ form.name(class="form-control", placeholder="Введите имя", required=true) }}
            <br>
            <label for="email">Email:</label>
            {{ form.email(class="form-control", placeholder="Введите email", required=true) }}
            <br>
            <label for="password">Пароль:</label>
            {{ form.password(class="form-control", placeholder="Введите пароль", required=true, minlength=4) }}
            <br>
            <label for="confirm_password">Подтверждение пароля:</label>
            {{ form.confirm_password(class="form-control", placeholder="Подтвердите пароль", required=true) }}

            {% if form.confirm_password.errors %}
                <p style="color: red;">Пароли в полях разные</p>
            {% endif %}

            <br>
            {{ form.submit(class="btn btn-primary") }}
        </form>
        <br>
        <p>Уже есть аккаунт? <a href="{{ url_for('users.login') }}">Авторизируйтесь здесь</a>.</p>
    </main>
</body>
</html>